package no.ordbokene.model.json.lookup.ids

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class GrammarId {
  @SerialName("bf") BF,
  @SerialName("forst") FORST,
  @SerialName("ent") ENT,
  @SerialName("adj") ADJ,
  @SerialName("adv") ADV,
  @SerialName("s_adj") S_ADJ,
  @SerialName("fl") FL,
  @SerialName("s_subst") S_SUBST,
  @SerialName("s_adv") S_ADV,
  @SerialName("prep") PREP,
  @SerialName("inf") INF,
  @SerialName("pf_pt") PF_PT,
  @SerialName("pret") PRET,
  @SerialName("subst") SUBST,
  @SerialName("refl") REFL,
  @SerialName("n") N,
  @SerialName("pr_pt") PR_PT,
  @SerialName("gramm") GRAMM,
  @SerialName("suff") SUFF,
  @SerialName("pron") PRON,
  @SerialName("komp") KOMP,
  @SerialName("superl") SUPERL,
  @SerialName("pass") PASS,
  @SerialName("konj") KONJ,
  @SerialName("tr") TR,
  @SerialName("intr") INTR,
  @SerialName("gen") GEN,
  @SerialName("dat") DAT,
  @SerialName("interj") INTERJ,
  @SerialName("akk") AKK,
  @SerialName("subst_t") SUBST_T,
  @SerialName("f") F,
  @SerialName("mask") MASK,
  @SerialName("upers") UPERS,
  @SerialName("subj") SUBJ,
  @SerialName("eint") EINT,
  @SerialName("uboey") UBOEY,
  @SerialName("subs_isk") SUBS_ISK,
  @SerialName("pr") PR,
  @SerialName("dim") DIM,
  @SerialName("pt") PT,
  @SerialName("pf") PF,
  @SerialName("subst_isk") SUBST_ISK,
  @SerialName("adjsk") ADJSK,
  @SerialName("ub") UB,
}
